package com.seetuned.companion.core

/**
 * All text the app shows, Hebrew first (like the web app) and English. Menu names stay in English quotes, as in
 * the web guide (engine/strings/guide-strings.js), because phones show them in their own language.
 * No clinical notation anywhere. StringsTest checks both languages have the same keys and placeholders.
 */
object Strings {
    fun of(lang: String): T = T(if (lang == "en") EN else HE)

    class T internal constructor(private val table: Map<String, String>) {
        /** `t("k", "pct" to 150)` → the text with {pct} replaced. A missing key returns the key itself. */
        operator fun invoke(key: String, vararg params: Pair<String, Any>): String {
            var s = table[key] ?: return key
            for ((k, v) in params) s = s.replace("{$k}", v.toString())
            return s
        }

        fun has(key: String): Boolean = key in table
    }

    val HE: Map<String, String> = mapOf(
        "app.title" to "SeeTuned",
        "app.subtitle" to "התאמת כל הטלפון לעיניים שלכם",
        "state.noRecipe" to "כדי להתחיל, פתחו את SeeTuned והשלימו את בדיקת הראייה. אחר כך, במסך ״התאמת הטלפון כולו״, הקישו על ״פתיחה באפליקציית SeeTuned לאנדרואיד״.",
        "state.tooNew" to "הקישור נוצר בגרסה חדשה יותר של SeeTuned. עדכנו את האפליקציה הזו ופתחו אותו שוב.",
        "state.invalid" to "הקישור לא תקין. פתחו אותו שוב מתוך SeeTuned.",
        "state.received" to "ההגדרות שהתאמנו לכם בבדיקה התקבלו. הן כוללות רק ערכי תצוגה.",
        "access.title" to "שלב 1: אישור גישה",
        "access.body" to "כדי לשנות את גודל הטקסט בכל הטלפון, SeeTuned צריכה את ההרשאה ״שינוי הגדרות המערכת״. בחלון שייפתח, הפעילו את המתג ליד SeeTuned וחזרו לכאן.",
        "access.allow" to "אישור גישה",
        "access.granted" to "הגישה אושרה.",
        "apply.all" to "החלת כל ההמלצות",
        "apply.one" to "החלה",
        "apply.done" to "הוחלו {n} הגדרות. ההגדרות שנשארו מסומנות ״לשנות בעצמכם״.",
        "apply.nothing" to "אין הגדרות שאפשר להחיל אוטומטית כרגע. אשרו גישה, או פתחו כל מסך ושנו בעצמכם.",
        "apply.failed" to "הטלפון לא אפשר לשנות חלק מההגדרות אוטומטית. פתחו את המסך ושנו בעצמכם.",
        "items.title" to "מה משתנה בטלפון",
        "item.TEXT_SIZE.title" to "גודל הטקסט בכל הטלפון",
        "item.DISPLAY_SIZE.title" to "הגדלת כל התצוגה",
        "item.BOLD.title" to "טקסט מודגש",
        "item.CONTRAST.title" to "ניגודיות מוגברת",
        "item.COLOR.title" to "מסנן צבע (לא חובה)",
        "item.DIM.title" to "עמעום צבעים בהירים",
        "item.DARK.title" to "מצב כהה",
        "item.MAGNIFICATION.title" to "קיצור להגדלה",
        "item.LENS.title" to "עדשת SeeTuned לכל מסך",
        "value.label" to "הערך:",
        "value.text" to "{pct}% מהגודל הרגיל",
        "value.display" to "{n} שלבים לכיוון הגדול",
        "value.displayMax" to "הגדול ביותר",
        "value.on" to "מופעל",
        "value.dark" to "כהה",
        "option.samsung.protan" to "אדום–ירוק (red–green)",
        "option.samsung.deutan" to "ירוק–אדום (green–red)",
        "option.samsung.tritan" to "כחול–צהוב (blue–yellow)",
        "option.android.protan" to "Red-green, red weak",
        "option.android.deutan" to "Red-green, green weak",
        "option.android.tritan" to "Blue-yellow",
        "level.medium" to "Medium",
        "level.high" to "High",
        "status.applied" to "הוחל",
        "status.pending" to "עוד לא הוחל",
        "status.needsAccess" to "צריך לאשר גישה (שלב 1)",
        "status.guided" to "לשנות בעצמכם: פתחו את המסך ובחרו את הערך",
        "status.optional" to "לא חובה. נסו ובחרו מה נוח לכם.",
        "status.lensOn" to "פועלת",
        "status.lensOff" to "כבויה",
        "button.open" to "פתיחת המסך בהגדרות",
        "where.samsung.TEXT_SIZE" to "הגדרות › \"Display\" › \"Font size and style\": הזיזו את המחוון \"Font size\" עד שטקסט הדוגמה גדול בכ-{pct}% מהרגיל.",
        "where.samsung.DISPLAY_SIZE" to "הגדרות › \"Display\" › \"Screen zoom\": הזיזו את המחוון {n} שלבים לכיוון הגדול.",
        "where.samsung.DISPLAY_SIZE_MAX" to "הגדרות › \"Display\" › \"Screen zoom\": הזיזו את המחוון להגדרה הגדולה ביותר.",
        "where.samsung.BOLD" to "הגדרות › \"Display\" › \"Font size and style\": הפעילו את \"Bold font\".",
        "where.samsung.CONTRAST" to "הגדרות › \"Accessibility\" › \"Vision enhancements\": הפעילו את \"High contrast fonts\".",
        "where.samsung.COLOR" to "הגדרות › \"Accessibility\" › \"Vision enhancements\" › \"Color correction\": הפעילו ובחרו {option}.",
        "where.samsung.DIM" to "הגדרות › \"Accessibility\" › \"Vision enhancements\": הפעילו את \"Extra dim\".",
        "where.samsung.DARK" to "הגדרות › \"Display\": בחרו \"Dark\".",
        "where.samsung.MAGNIFICATION" to "הגדרות › \"Accessibility\" › \"Vision enhancements\" › \"Magnification\": הפעילו קיצור להגדלה.",
        "where.android.TEXT_SIZE" to "הגדרות › \"Accessibility\" › \"Display size and text\": הזיזו את \"Font size\" ל-{pct}%.",
        "where.android.DISPLAY_SIZE" to "הגדרות › \"Accessibility\" › \"Display size and text\": הזיזו את \"Display size\" {n} שלבים לכיוון הגדול.",
        "where.android.DISPLAY_SIZE_MAX" to "הגדרות › \"Accessibility\" › \"Display size and text\": הזיזו את \"Display size\" להגדרה הגדולה ביותר.",
        "where.android.BOLD" to "הגדרות › \"Accessibility\" › \"Display size and text\": הפעילו את \"Bold text\".",
        "where.android.CONTRAST" to "הגדרות › \"Accessibility\" › \"Display size and text\": הפעילו את \"High contrast text\". ב-Android 15 ואילך גם: \"Color and motion\" › \"Color contrast\" › \"{level}\".",
        "where.android.COLOR" to "הגדרות › \"Accessibility\" › \"Color and motion\" › \"Color correction\": הפעילו ובחרו \"{option}\".",
        "where.android.DIM" to "הגדרות › \"Accessibility\" › \"Extra dim\": הפעילו.",
        "where.android.DARK" to "הגדרות › \"Accessibility\" › \"Color and motion\": הפעילו את \"Dark theme\".",
        "where.android.MAGNIFICATION" to "הגדרות › \"Accessibility\" › \"Magnification\": הפעילו את \"Magnification shortcut\".",
        "note.FONT_CAPPED" to "גרסת האנדרואיד בטלפון הזה מגיעה עד {max}%, ולכן מומלץ להגדיל גם את כל התצוגה.",
        "note.FONT_EXCEEDS" to "גם הגודל הזה קטן מהמומלץ לכם, ולכן כדאי להוסיף הגדלה של כל התצוגה וקיצור להגדלה.",
        "advanced.title" to "החלה אוטומטית של שאר ההגדרות (למתקדמים)",
        "advanced.body" to "טקסט מודגש, ניגודיות, מסנן צבע ועמעום דורשים הרשאה שאנדרואיד נותן רק דרך מחשב. מי שמכיר את כלי הפיתוח של אנדרואיד (adb) יכול לתת אותה פעם אחת עם הפקודה הזו, ואז ההגדרות האלה יוחלו אוטומטית:",
        "advanced.copy" to "העתקת הפקודה",
        "advanced.copied" to "הפקודה הועתקה.",
        "advanced.granted" to "ההרשאה המתקדמת פעילה: גם ההגדרות האלה מוחלות אוטומטית.",
        "restore.title" to "חזרה להגדרות המקוריות",
        "restore.body" to "SeeTuned שמרה את ההגדרות שהיו לכם לפני השינוי. אפשר להחזיר אותן בכל רגע.",
        "restore.button" to "החזרת ההגדרות המקוריות",
        "restore.done" to "ההגדרות המקוריות הוחזרו.",
        "restore.partial" to "חלק מההגדרות לא הוחזרו, כי ההרשאה בוטלה בינתיים. אשרו גישה ונסו שוב.",
        "lens.body" to "מגדילה ומחדדת כל מה שמוצג על המסך, בכל אפליקציה: הודעות, אתרים, תמונות ועצירה של סרטון. מקישים על לחצן הנגישות או על ״עדשת SeeTuned״ בלוח ההגדרות המהירות.",
        "lens.enable" to "הפעלת העדשה",
        "lens.disclosure.title" to "לפני שמפעילים את העדשה",
        "lens.disclosure.body" to "העדשה משתמשת בשירות הנגישות של אנדרואיד. רק כשאתם מקישים עליה, היא מצלמת את מה שמוצג על המסך באותו רגע, משפרת את התמונה לפי ההגדרות שלכם ומציגה אותה מוגדלת. התמונה נשארת בטלפון: היא לא נשמרת ולא נשלחת לשום מקום. העדשה לא קוראת את התוכן של אפליקציות אחרות ולא פועלת בלי שתקישו עליה.",
        "lens.disclosure.agree" to "מסכימים, להמשך",
        "lens.disclosure.cancel" to "לא עכשיו",
        "lens.howTo" to "במסך שייפתח, הקישו על ״עדשת SeeTuned״ והפעילו אותה. שם אפשר גם לבחור קיצור: לחצן הנגישות או מקשי עוצמת הקול.",
        "lens.close" to "סגירה",
        "lens.original" to "להשוואה: המקור",
        "lens.enhanced" to "חזרה לתצוגה המשופרת",
        "lens.preparing" to "מכינים את התצוגה…",
        "lens.error" to "לא הצלחנו לצלם את המסך. נסו שוב בעוד רגע.",
        "lens.secure" to "אם חלק מהמסך שחור, האפליקציה שמאחור מוגנת (למשל בנק או סרט), ואי אפשר להציג אותה.",
        "lens.hint" to "צבטו כדי להגדיל, גררו כדי לזוז, והקישו פעמיים כדי להגדיל או להקטין.",
        "lens.unavailable" to "העדשה דורשת Android 11 ומעלה.",
        "footer.disclaimer" to "SeeTuned היא כלי להתאמת תצוגה ולנוחות צפייה. היא לא מכשיר רפואי, לא אבחנה ולא מרשם.",
    )

    val EN: Map<String, String> = mapOf(
        "app.title" to "SeeTuned",
        "app.subtitle" to "Tune your whole phone to your eyes",
        "state.noRecipe" to "To start, open SeeTuned and complete the vision check. Then, on “Adapt my whole phone”, tap “Open in the SeeTuned Android app”.",
        "state.tooNew" to "This link comes from a newer version of SeeTuned. Update this app and open the link again.",
        "state.invalid" to "This link isn’t valid. Open it again from SeeTuned.",
        "state.received" to "We received the settings tuned to you in the check. They contain display values only.",
        "access.title" to "Step 1: give access",
        "access.body" to "To change the text size across your phone, SeeTuned needs the “Modify system settings” permission. In the screen that opens, turn on the switch next to SeeTuned, then come back here.",
        "access.allow" to "Give access",
        "access.granted" to "Access granted.",
        "apply.all" to "Apply all recommendations",
        "apply.one" to "Apply",
        "apply.done" to "{n} settings applied. The rest are marked “change it yourself”.",
        "apply.nothing" to "Nothing can be applied automatically yet. Give access, or open each screen and change it yourself.",
        "apply.failed" to "Your phone didn’t allow some settings to change automatically. Open the screen and change them yourself.",
        "items.title" to "What changes on your phone",
        "item.TEXT_SIZE.title" to "Text size across the phone",
        "item.DISPLAY_SIZE.title" to "Make everything bigger",
        "item.BOLD.title" to "Bold text",
        "item.CONTRAST.title" to "Higher contrast",
        "item.COLOR.title" to "Colour filter (optional)",
        "item.DIM.title" to "Dim bright colours",
        "item.DARK.title" to "Dark mode",
        "item.MAGNIFICATION.title" to "Zoom shortcut",
        "item.LENS.title" to "SeeTuned lens for any screen",
        "value.label" to "Value:",
        "value.text" to "{pct}% of the standard size",
        "value.display" to "{n} step(s) larger",
        "value.displayMax" to "The largest",
        "value.on" to "On",
        "value.dark" to "Dark",
        "option.samsung.protan" to "Red–green",
        "option.samsung.deutan" to "Green–red",
        "option.samsung.tritan" to "Blue–yellow",
        "option.android.protan" to "Red-green, red weak",
        "option.android.deutan" to "Red-green, green weak",
        "option.android.tritan" to "Blue-yellow",
        "level.medium" to "Medium",
        "level.high" to "High",
        "status.applied" to "Applied",
        "status.pending" to "Not applied yet",
        "status.needsAccess" to "Needs access (step 1)",
        "status.guided" to "Change it yourself: open the screen and pick the value",
        "status.optional" to "Optional. Try it and keep what feels better.",
        "status.lensOn" to "On",
        "status.lensOff" to "Off",
        "button.open" to "Open this screen in Settings",
        "where.samsung.TEXT_SIZE" to "Settings › “Display” › “Font size and style”: move “Font size” until the sample text is about {pct}% of normal.",
        "where.samsung.DISPLAY_SIZE" to "Settings › “Display” › “Screen zoom”: move the slider {n} step(s) toward larger.",
        "where.samsung.DISPLAY_SIZE_MAX" to "Settings › “Display” › “Screen zoom”: move the slider to the largest setting.",
        "where.samsung.BOLD" to "Settings › “Display” › “Font size and style”: turn on “Bold font”.",
        "where.samsung.CONTRAST" to "Settings › “Accessibility” › “Vision enhancements”: turn on “High contrast fonts”.",
        "where.samsung.COLOR" to "Settings › “Accessibility” › “Vision enhancements” › “Color correction”: turn it on and choose {option}.",
        "where.samsung.DIM" to "Settings › “Accessibility” › “Vision enhancements”: turn on “Extra dim”.",
        "where.samsung.DARK" to "Settings › “Display”: choose “Dark”.",
        "where.samsung.MAGNIFICATION" to "Settings › “Accessibility” › “Vision enhancements” › “Magnification”: turn on a magnification shortcut.",
        "where.android.TEXT_SIZE" to "Settings › “Accessibility” › “Display size and text”: set “Font size” to {pct}%.",
        "where.android.DISPLAY_SIZE" to "Settings › “Accessibility” › “Display size and text”: move “Display size” {n} step(s) toward larger.",
        "where.android.DISPLAY_SIZE_MAX" to "Settings › “Accessibility” › “Display size and text”: move “Display size” to the largest setting.",
        "where.android.BOLD" to "Settings › “Accessibility” › “Display size and text”: turn on “Bold text”.",
        "where.android.CONTRAST" to "Settings › “Accessibility” › “Display size and text”: turn on “High contrast text”. On Android 15 and later also: “Color and motion” › “Color contrast” › “{level}”.",
        "where.android.COLOR" to "Settings › “Accessibility” › “Color and motion” › “Color correction”: turn it on and choose “{option}”.",
        "where.android.DIM" to "Settings › “Accessibility” › “Extra dim”: turn it on.",
        "where.android.DARK" to "Settings › “Accessibility” › “Color and motion”: turn on “Dark theme”.",
        "where.android.MAGNIFICATION" to "Settings › “Accessibility” › “Magnification”: turn on “Magnification shortcut”.",
        "note.FONT_CAPPED" to "The Android version on this phone goes up to {max}%, so also make everything bigger.",
        "note.FONT_EXCEEDS" to "Even this size is smaller than recommended for you, so also make everything bigger and add a zoom shortcut.",
        "advanced.title" to "Apply the other settings automatically (advanced)",
        "advanced.body" to "Bold text, contrast, the colour filter and dimming need a permission Android grants only from a computer. If you know Android’s developer tools (adb), grant it once with this command and these settings will apply automatically too:",
        "advanced.copy" to "Copy the command",
        "advanced.copied" to "Command copied.",
        "advanced.granted" to "Advanced access is on: these settings apply automatically too.",
        "restore.title" to "Back to your original settings",
        "restore.body" to "SeeTuned saved the settings you had before. You can bring them back at any time.",
        "restore.button" to "Restore my original settings",
        "restore.done" to "Your original settings are back.",
        "restore.partial" to "Some settings weren’t restored because the access was turned off. Give access and try again.",
        "lens.body" to "Enlarges and sharpens whatever is on screen, in any app: messages, websites, photos and a paused video. Tap the accessibility button, or “SeeTuned lens” in Quick Settings.",
        "lens.enable" to "Turn on the lens",
        "lens.disclosure.title" to "Before you turn on the lens",
        "lens.disclosure.body" to "The lens uses Android’s accessibility service. Only when you tap it, it takes a picture of what is on screen at that moment, improves it with your settings and shows it enlarged. The picture stays on your phone: it isn’t saved or sent anywhere. The lens doesn’t read other apps’ content and does nothing until you tap it.",
        "lens.disclosure.agree" to "Agree and continue",
        "lens.disclosure.cancel" to "Not now",
        "lens.howTo" to "In the screen that opens, tap “SeeTuned lens” and turn it on. There you can also choose a shortcut: the accessibility button or the volume keys.",
        "lens.close" to "Close",
        "lens.original" to "Compare: original",
        "lens.enhanced" to "Back to the enhanced view",
        "lens.preparing" to "Preparing the view…",
        "lens.error" to "We couldn’t capture the screen. Try again in a moment.",
        "lens.secure" to "If part of the screen is black, the app behind is protected (a bank or a film, for example) and can’t be shown.",
        "lens.hint" to "Pinch to zoom, drag to move, and double-tap to zoom in or out.",
        "lens.unavailable" to "The lens needs Android 11 or later.",
        "footer.disclaimer" to "SeeTuned is a display-adjustment and viewing-comfort tool. It is not a medical device, a diagnosis or a prescription.",
    )
}
