// @ts-check
/**
 * Golden vectors for the Android screen lens (android/core LensMath.kt).
 *
 * Each case is a small RGBA image, the lens parameters exactly as the web app sends them to the Android app
 * (buildAndroidRecipe → query string), and the output of the JavaScript reference pipeline (processImageData).
 * LensMathTest parses the query with RecipeCodec and must reproduce every pixel within ±1 of 255.
 *
 *   node scripts/android/lens-golden.js      rewrites android/core/src/test/resources/lens-golden.json
 * test/unit/render/lens-golden.test.js fails when the committed file no longer matches the JavaScript pipeline.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { processImageData } from '../../public/app/js/render/filter-math.js';
import { buildAndroidRecipe } from '../../public/app/js/engine/android-link.js';

export const GOLDEN_PATH = fileURLToPath(new URL('../../android/core/src/test/resources/lens-golden.json', import.meta.url));

/** Deterministic PRNG (mulberry32). @param {number} seed */
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Text-like test image: dark strokes on light ground, a colour band, noise, and a few translucent pixels. */
function makeImage(width, height, seed) {
  const rand = rng(seed);
  const data = new Uint8ClampedArray(width * height * 4);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const i = (y * width + x) * 4;
      const stroke = (x % 5 === 1 || y % 6 === 2) && rand() > 0.25;
      const band = y >= height - 4;
      const v = stroke ? 30 + rand() * 40 : 200 + rand() * 55;
      data[i] = band ? (x * 11) % 256 : v;
      data[i + 1] = band ? 120 + rand() * 60 : v * (0.95 + rand() * 0.05);
      data[i + 2] = band ? 255 - ((x * 7) % 256) : v * (0.9 + rand() * 0.1);
      data[i + 3] = (x + y * 3) % 29 === 0 ? 128 : (x * y) % 41 === 7 ? 0 : 255;
    }
  }
  return data;
}

const DEUTAN_LIKE = [1.1, -0.06, -0.04, 0.12, 0.84, 0.04, -0.03, 0.1, 0.93];

export const CASES = [
  { name: 'neutral', sigma: 2, media: {} },
  { name: 'tone only', sigma: 2, media: { contrast: 1.3, brightness: 1.1, saturation: 0.8, warmth: 0.4 } },
  { name: 'colour matrix and sharpening', sigma: 2, media: { colorMatrix: DEUTAN_LIKE, sharpenAmount: 1.2, sharpenSigmaPx: 1.5, contrast: 1.15 } },
  { name: 'invert, high contrast, fine sharpening', sigma: 2.1, media: { invert: true, contrast: 1.5, sharpenAmount: 0.5, sharpenSigmaPx: 0.8 } },
  { name: 'sigma clamped to 20 px', sigma: 30, media: { sharpenAmount: 2, sharpenSigmaPx: 12, saturation: 1.4 } },
];

export function generateLensGolden() {
  const width = 23;
  const height = 17;
  return {
    note: 'Generated by scripts/android/lens-golden.js from public/app/js/render/filter-math.js. Do not edit.',
    width,
    height,
    cases: CASES.map((c, k) => {
      const input = makeImage(width, height, 1000 + k);
      const query = buildAndroidRecipe({ media: /** @type {any} */ (c.media) }, 'he').toString();
      const out = processImageData(new Uint8ClampedArray(input), width, height, c.media, c.sigma);
      const rgb = [];
      for (let i = 0; i < width * height; i++) rgb.push(out[i * 4], out[i * 4 + 1], out[i * 4 + 2]);
      return { name: c.name, query, sigma: c.sigma, input: Array.from(input), output: rgb };
    }),
  };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(GOLDEN_PATH, JSON.stringify(generateLensGolden()) + '\n');
  console.log(`wrote ${GOLDEN_PATH}`);
}
